In [1]:
import os

import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.15.0


In [2]:
import tensorflow as tf




a = tf.constant([[10,10],[11,1.]])
x = tf.constant([[1.,0.],[0.,1.]])
b = tf.Variable(12.)
y = tf.matmul(a, x) + b

print(a)
print(x)
print(b)
print(y.numpy())

tf.Tensor(
[[10. 10.]
 [11.  1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=12.0>
[[22. 22.]
 [23. 13.]]


In [3]:
import tensorflow as tf

# Create a constant tensor
a = tf.constant(3.0)

# Print the constant tensor
print(a)


tf.Tensor(3.0, shape=(), dtype=float32)


In [6]:
# 宣告變數    
b = tf.Variable(0, dtype=tf.int64)
c = tf.Variable(2.0)
# Print the constant tensor
print(b)
print(c)

<tf.Variable 'Variable:0' shape=() dtype=int64, numpy=0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>


In [10]:
# 宣告變數    
b = tf.Variable(0, dtype=tf.int64)
b.assign(7)
# Print the constant tensor
print(b)
print(b.numpy())

<tf.Variable 'Variable:0' shape=() dtype=int64, numpy=7>
7


In [14]:
import tensorflow as tf

# Define variables with names
var1 = tf.Variable(1.0, name="my_variable_1")
var2 = tf.Variable(2.0, name="my_variable_2")

# Use variable names in the computation graph
result = var1 + var2

# Print the variable names
print("Variable 1 name:", var1.name)
print("Variable 2 name:", var2.name)

print(var1)
print(var2)
print(result)



Variable 1 name: my_variable_1:0
Variable 2 name: my_variable_2:0
<tf.Variable 'my_variable_1:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'my_variable_2:0' shape=() dtype=float32, numpy=2.0>
tf.Tensor(3.0, shape=(), dtype=float32)


In [15]:

x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 4 values, but the requested shape has 3 [Op:Reshape]